# Generated by Django 3.2.9 on 2022-01-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
