# Generated by Django 3.2.9 on 2022-01-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djecommerce', '0002_remove_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='djecommerce.customer'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.IntegerField(choices=[(0, 'Apple Iphone 11'), (1, 'Apple Iphone 12'), (2, 'Samsung 10'), (3, 'Sony 13')], null=True, verbose_name='Phone Model'),
        ),
    ]
