# Generated by Django 3.2.9 on 2022-01-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djecommerce', '0003_customer'),
        ('djecommerce', '0003_feedback'),
    ]

    operations = [
    ]
