# Generated by Django 3.2.9 on 2022-01-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djecommerce', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
