# Generated by Django 3.2.9 on 2022-01-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djecommerce', '0004_merge_0003_customer_0003_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
