# Generated by Django 3.2.9 on 2022-01-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djecommerce', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
