# Generated by Django 3.2.9 on 2022-01-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djecommerce', '0007_auto_20220118_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateField(null=True, verbose_name='Date of Order'),
        ),
    ]
