# Generated by Django 3.2.9 on 2022-01-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djecommerce', '0008_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=0),
        ),
    ]
