# Generated by Django 3.2.9 on 2022-01-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djecommerce', '0009_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(default=0),
        ),
    ]
