# Generated by Django 3.2.9 on 2022-01-20 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djecommerce', '0011_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='djecommerce.customer'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djecommerce.product'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
